package com.t4u.crm.bean;

// Generated Oct 18, 2013 10:45:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;

import org.hibernate.annotations.Type;

/**
 * T4uWorkStatus generated by hbm2java
 */
@Entity
@Table(name = "t4u_work_status", catalog = "t4u_db")
public class WorkStatus implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int statusId;
	
	private String statusName;
	
	@Column( columnDefinition = "TINYINT(1)")
	private boolean activeFlag;
	private String description;
	@ManyToOne
	private User createdUser;
	@ManyToOne
	private User updatedUser;
	@OneToMany(mappedBy="workStatus",fetch=FetchType.LAZY)
	private Set<Oppurtunity> oppurtunities = new HashSet<Oppurtunity>();

	public int getStatusId() {
		return statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public boolean getActiveFlag() {
		return activeFlag;
	}

	public void setActiveFlag(boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public User getCreatedUser() {
		return createdUser;
	}

	public void setCreatedUser(User createdUser) {
		this.createdUser = createdUser;
	}

	public User getUpdatedUser() {
		return updatedUser;
	}

	public void setUpdatedUser(User updatedUser) {
		this.updatedUser = updatedUser;
	}

	public Set<Oppurtunity> getOppurtunities() {
		return oppurtunities;
	}

	public void setOppurtunities(Set<Oppurtunity> oppurtunities) {
		this.oppurtunities = oppurtunities;
	}

}
