package com.t4u.bean;// default package
// Generated Oct 18, 2013 10:45:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * T4uAudit generated by hbm2java
 */
@Entity
@Table(name = "T4U_AUDIT", catalog = "T4U_DB")
public class Audit implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="AUDIT_ID")
	private int auditId;
	@Column(name="TABLE_NAME")
	private String tableName;
	@Column(name="TABLE_PRI_KEY_ID")
	private String tablePriKeyId;
	@Column(name="COLUMN_NAME")
	private String columnName;
	@Column(name="NEW_VALUE")
	private String newValue;
	@Column(name="OLD_VALUE")
	private String oldValue;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="UPDATE_TIMESTAMP")
	private Date updateTimestamp;
	
	@ManyToOne
	@JoinColumn(name="UPDATED_USER_ID")
	private User updatedUser;
	public int getAuditId() {
		return auditId;
	}
	public void setAuditId(int auditId) {
		this.auditId = auditId;
	}
	public String getTableName() {
		return tableName;
	}
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	public String getTablePriKeyId() {
		return tablePriKeyId;
	}
	public void setTablePriKeyId(String tablePriKeyId) {
		this.tablePriKeyId = tablePriKeyId;
	}
	public String getColumnName() {
		return columnName;
	}
	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}
	public String getNewValue() {
		return newValue;
	}
	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}
	public String getOldValue() {
		return oldValue;
	}
	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}
	public Date getCreateTimestamp() {
		return updateTimestamp;
	}
	public void setCreateTimestamp(Date createTimestamp) {
		this.updateTimestamp = createTimestamp;
	}
	
	public User getUpdatedUser() {
		return updatedUser;
	}
	public void setUpdatedUser(User updatedUser) {
		this.updatedUser = updatedUser;
	}

}
